name: stock_management
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.7
  cupertino_icons: ^0.1.3
  lottie: ^0.7.0+1
  shared_preferences: ^0.5.12+2
  get_it: ^5.0.1
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^0.6.7
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animation/lottie/
  fonts:
    - family: NanumGothic-Bold
      fonts:
        - asset: assets/fonts/NanumGothic-Bold.ttf
    - family: NanumGothic-Regular
      fonts:
        - asset: assets/fonts/NanumGothic-Regular.ttf
